### ISSUE TITLE
Не работает команда /support (если не заполнены поля lastname и username в профиле)

### ISSUE THREAD

**Issue by NKozlov** [NKozlov/lanit-bus-bot#6]
```
14:04:40 DEBUG LiveEnvironment {pro.nkozlov.telegram.bots.lanitbus.LanitBusBot$ $anonfun$new$36} - execute command '/support' from Message(503,Some(User(108839202,tmf,None,None)),1482318279,Chat(108839202,private,None,None,Some(tmf),None,None),None,None,None,None,None,None,Some(/support),Some(List(MessageEntity(bot_command,0,8,None,None))),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)
14:04:40 ERROR LiveEnvironment {info.mukel.telegrambot4s.api.Polling $anonfun$run$2} - Caught exception in update handler
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at pro.nkozlov.telegram.bots.lanitbus.LanitBusBot$.$anonfun$new$36(LanitBusBot.scala:121)
	at pro.nkozlov.telegram.bots.lanitbus.LanitBusBot$.$anonfun$new$36$adapted(LanitBusBot.scala:118)
	at info.mukel.telegrambot4s.api.Commands.$anonfun$onMessage$4(Commands.scala:37)
	at info.mukel.telegrambot4s.api.Commands.$anonfun$onMessage$4$adapted(Commands.scala:35)
	at scala.Option$WithFilter.map(Option.scala:146)
	at info.mukel.telegrambot4s.api.Commands.$anonfun$onMessage$2(Commands.scala:35)
	at scala.Option.flatMap(Option.scala:171)
	at info.mukel.telegrambot4s.api.Commands.onMessage(Commands.scala:33)
	at info.mukel.telegrambot4s.api.Commands.onMessage$(Commands.scala:25)
	at pro.nkozlov.telegram.bots.lanitbus.LanitBusBot$.onMessage(LanitBusBot.scala:8)
	at info.mukel.telegrambot4s.api.BotBase.$anonfun$onUpdate$1(BotBase.scala:28)
	at info.mukel.telegrambot4s.api.BotBase.$anonfun$onUpdate$1$adapted(BotBase.scala:28)
	at scala.Option.foreach(Option.scala:257)
	at info.mukel.telegrambot4s.api.BotBase.onUpdate(BotBase.scala:28)
	at info.mukel.telegrambot4s.api.BotBase.onUpdate$(BotBase.scala:27)
	at pro.nkozlov.telegram.bots.lanitbus.LanitBusBot$.onUpdate(LanitBusBot.scala:8)
	at info.mukel.telegrambot4s.api.Polling.$anonfun$run$2(Polling.scala:60)
	at info.mukel.telegrambot4s.api.Polling.$anonfun$run$2$adapted(Polling.scala:58)
	at akka.stream.impl.fusing.Map$$anon$8.onPush(Ops.scala:43)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:484)
	at akka.actor.Actor.aroundReceive$(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by NKozlov** [comment]
Fixed.
